tastetag_main_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TastetagMainBundle:Default:index }
homepage:
    pattern:  /home
    defaults: { _controller: "TastetagMainBundle:Home:index" }
recipe_new:
    pattern:  /recipes/new
    defaults: { _controller: "TastetagMainBundle:Recipes:new" }
recipe_create:
    pattern:  /recipes/create
    defaults: { _controller: "TastetagMainBundle:Recipes:create" }
    requirements: { _method: post }
recipe_show:
    pattern:  /recipes/{id}
    defaults: { _controller: "TastetagMainBundle:Recipes:show" }
recipe_edit:
    pattern:  /recipes/{id}/edit
    defaults: { _controller: "TastetagMainBundle:Recipes:edit" }
recipe_update:
    pattern:  /recipes/{id}/update
    defaults: { _controller: "TastetagMainBundle:Recipes:update" }
    requirements: { _method: post }
recipe_delete:
    pattern:  /recipes/{id}/delete
    defaults: { _controller: "TastetagMainBundle:Recipes:delete" }
    requirements: { _method: post }
recipe_comment_create:
    pattern:  /recipes/{recipe_id}/comment/create
    defaults: { _controller: TastetagMainBundle:Comments:create }
    requirements:
        recipe_id: \d+
        _method:  POST
recipe_comment_new:
    pattern:  /recipes/{recipe_id}/comment/new
    defaults: { _controller: TastetagMainBundle:Comments:new }
    requirements:
        recipe_id: \d+
tag_recipes:
    pattern:  /tag/{id}
    defaults: { _controller: "TastetagMainBundle:Tags:recipes" }
account_register:
    path:     /register
    defaults: { _controller: TastetagMainBundle:User:register }
account_create:
    pattern:     /register/create
    defaults: { _controller: TastetagMainBundle:User:create }
login:
    pattern:   /login
    defaults:  { _controller: TastetagMainBundle:Home:login }
login_check:
    pattern:   /login_check
logout:
    pattern: /logout
user_profile:
    pattern:  /profile/{user_id}
    defaults: { _controller: TastetagMainBundle:User:profile }