jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default

    encoders:
        Tastetag\MainBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            entity: 
                class: Tastetag\MainBundle\Entity\User
                property: username 

    firewalls:
        # dev:
        #     pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #     security: false

        # login:
        #     pattern:  ^/login$
        #     security: false

        secured_area:
            pattern:    /.*
            provider: main
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /home
            logout:
                path:   /logout
                target: /home
            anonymous: ~
            # http_basic:
            #     realm: "Secured Demo Area"
        # main:
        #     pattern: /.*
        #     form_login:
        #         login_path: /login
        #         check_path: /login_check
        #     logout:
        #         path: /logout
        #         target: /
        #     security: true
        #     anonymous: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recipes/new, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }